# Generated by Django 5.2.15 on 2026-07-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='account_id',
        ),
    ]
